import { expect, test } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { resolve } from 'node:path';
const backendRequire = createRequire(resolve('functions/package.json'));
const { initializeApp } = backendRequire('firebase-admin/app');
const { getAuth } = backendRequire('firebase-admin/auth');
const { getFirestore } = backendRequire('firebase-admin/firestore');
process.env.FIREBASE_AUTH_EMULATOR_HOST = '127.0.0.1:9099';
process.env.FIRESTORE_EMULATOR_HOST = '127.0.0.1:8080';
const backend = initializeApp({ projectId: 'demo-sgo' });

test('administrador cadastra acesso, salva e edita OS; cliente acompanha dois veículos sem dados internos', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  await page.route('**/*', route => {
    const url = new URL(route.request().url());
    return ['127.0.0.1', 'localhost'].includes(url.hostname) || ['data:', 'blob:'].includes(url.protocol) ? route.continue() : route.abort('blockedbyclient');
  });
  const email = `admin-${Date.now()}@sgo.test`, password = 'Oficina123!';
  const account = await getAuth(backend).createUser({ email, password, displayName: 'Oficina' });
  await getAuth(backend).setCustomUserClaims(account.uid, { admin: true });
  await mkdir('docs/screenshots', { recursive: true });
  await page.goto('/');
  await expect(page.getByText('Acompanhe seu veículo', { exact: true })).toBeVisible();
  await page.screenshot({ path: 'docs/screenshots/login.png', fullPage: true });
  await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await expect(page.getByText('Informe uma placa válida e sua senha.')).toBeVisible();
  await page.getByRole('button', { name: 'Login administrativo' }).click();
  await page.getByLabel('E-mail', { exact: true }).fill(email);
  await page.getByLabel('Senha', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await expect(page.getByText('Olá, Oficina.')).toBeVisible();
  await page.getByRole('tab', { name: /Clientes/ }).click();
  await page.getByLabel('Nome do cliente', { exact: true }).fill('Ana Souza');
  await page.getByLabel('Telefone com DDD', { exact: true }).fill('51999999999');
  await page.getByRole('button', { name: 'Salvar cliente', exact: true }).click();
  await expect(page.getByText('Cliente salvo. Cadastre ou selecione um veículo.')).toBeVisible();
  for (const [plate, model] of [['ABC1D23', 'Onix 2020'], ['DEF1234', 'Gol 2018']]) {
    await page.getByLabel('Placa', { exact: true }).fill(plate!);
    await page.getByLabel('Modelo do veículo', { exact: true }).fill(model!);
    await page.getByRole('button', { name: 'Salvar veículo', exact: true }).click();
    await expect(page.getByText('Veículo salvo.', { exact: true })).toBeVisible();
    await page.getByLabel('Senha inicial do cliente', { exact: true }).fill('SenhaInicial123');
    await page.getByRole('button', { name: 'Criar acesso do cliente', exact: true }).click();
    await expect(page.getByText(`Acesso criado para ${plate}. O cliente usará a senha inicial e deverá criar uma nova senha.`)).toBeVisible();
    await expect(page.getByLabel('Senha inicial do cliente')).toHaveValue('');
  }
  await page.getByLabel('Modelo do veículo').fill('Gol 2019');
  await page.getByRole('button', { name: 'Salvar veículo', exact: true }).click();
  await expect(page.getByText('DEF1234 · Gol 2019', { exact: true })).toBeVisible();
  await page.getByRole('tab', { name: /Ordens/ }).click();
  await page.getByRole('button', { name: 'Nova ordem', exact: true }).click();
  await page.getByLabel('Placa', { exact: true }).filter({ visible: true }).fill('abc-1d23');
  await expect(page.getByLabel('Nome do cliente', { exact: true }).filter({ visible: true })).toHaveValue('Ana Souza');
  await page.getByLabel('Descrição do serviço', { exact: true }).fill('Reparar pintura do para-lama.');
  await page.getByLabel('Data de entrada', { exact: true }).fill('2026-09-18');
  await page.getByRole('button', { name: 'Definir previsão de entrega' }).click();
  await page.getByLabel('Previsão de entrega', { exact: true }).fill('2026-09-25');
  await page.getByLabel('Mão de obra (R$)', { exact: true }).fill('1.200,00');
  await page.getByLabel('Peças e materiais (R$)', { exact: true }).fill('350,50');
  await page.getByLabel('Observação pública', { exact: true }).fill('Veículo recebido com segurança.');
  await page.getByLabel('Informações internas', { exact: true }).fill('SEGREDO-OFICINA margem interna');
  await page.getByRole('button', { name: 'Salvar ordem de serviço' }).click();
  await expect(page.getByText('Andamento do reparo', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Editar ordem', exact: true }).click();
  await page.getByLabel('Observação pública', { exact: true }).fill('Prazo confirmado pela oficina.');
  await page.getByRole('button', { name: 'Salvar ordem de serviço' }).click();
  await expect(page.getByText('Prazo confirmado pela oficina.', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Atualizar andamento', exact: true }).click();
  await page.getByRole('button', { name: 'Em manutenção', exact: true }).click();
  await page.getByLabel('O que foi realizado?', { exact: true }).fill('Peça desmontada para avaliação.');
  await page.getByLabel('Data da atualização', { exact: true }).fill('2026-09-19');
  await page.getByRole('button', { name: 'Confirmar etapa' }).click();
  await expect(page.getByText('Etapa atualizada. O histórico do reparo foi salvo.')).toBeVisible();
  await page.getByRole('button', { name: 'Adicionar anexo', exact: true }).click();
  const chooser = page.waitForEvent('filechooser');
  await page.getByRole('button', { name: 'Selecionar arquivo', exact: true }).click();
  await (await chooser).setFiles({ name: 'reparo.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aB9sAAAAASUVORK5CYII=', 'base64') });
  await page.getByLabel('Descrição do anexo').fill('Antes do reparo');
  await page.getByRole('button', { name: 'Salvar anexo', exact: true }).click();
  await expect(page.getByText('Anexo salvo na ordem de serviço.')).toBeVisible();
  await page.getByRole('button', { name: 'Registrar pagamento', exact: true }).click();
  await expect(page.getByLabel('Descrição do pagamento', { exact: true })).toHaveValue('Pagamento ABC1D23 Ana Souza');
  await page.getByLabel('Valor pago (R$)', { exact: true }).fill('500,00');
  await page.getByRole('button', { name: 'Salvar pagamento', exact: true }).click();
  await expect(page.getByText('Pagamento registrado na ordem e no financeiro.')).toBeVisible();
  await page.screenshot({ path: 'docs/screenshots/ordem.png', fullPage: true });
  await page.reload();
  await expect(page.getByText('Olá, Oficina.')).toBeVisible();
  await page.getByRole('tab', { name: /Financeiro/ }).click();
  await page.getByRole('button', { name: 'Novo lançamento', exact: true }).click();
  await page.getByLabel('Descrição', { exact: true }).fill('Pagamento do Onix');
  await page.getByLabel('Valor (R$)', { exact: true }).fill('500,00');
  await page.getByRole('button', { name: 'Salvar lançamento', exact: true }).click();
  await expect(page.getByText('Pagamento do Onix')).toBeVisible();
  await page.getByRole('tab', { name: /Conta/ }).click();
  await page.getByRole('button', { name: 'Sair da conta', exact: true }).click();
  await page.getByRole('button', { name: 'Confirmar saída' }).click();
  await page.getByLabel('Placa do veículo').fill('abc-1d23');
  await page.getByLabel('Senha', { exact: true }).fill('SenhaInicial123');
  await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await expect(page.getByText('Crie sua nova senha')).toBeVisible();
  await page.getByLabel('Nova senha', { exact: true }).fill('Nova1234');
  await page.getByLabel('Confirmar nova senha', { exact: true }).fill('Nova1234');
  await page.getByRole('button', { name: 'Salvar nova senha' }).click();
  await expect(page.getByText('Acompanhe seu veículo', { exact: true })).toBeVisible();
  await page.getByLabel('Placa do veículo').fill('ABC1D23');
  await page.getByLabel('Senha', { exact: true }).fill('Nova1234');
  await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await expect(page.getByText('Meus veículos', { exact: true })).toBeVisible();
  await expect(page.getByText('Gol 2019', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Abrir ordem ABC1D23', exact: true }).click();
  await expect(page.getByText('Em manutenção', { exact: true }).first()).toBeVisible();
  await expect(page.getByText(/1\.550,50/).first()).toBeVisible();
  await expect(page.getByText(/1\.050,50/).first()).toBeVisible();
  await expect(page.getByText(/Peça desmontada/).first()).toBeVisible();
  await expect(page.getByText('Antes do reparo', { exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Abrir foto: reparo.png', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Adicionar anexo', exact: true })).toHaveCount(0);
  await expect(page.getByText(/SEGREDO-OFICINA/)).toHaveCount(0);
  await expect(page.getByRole('tab')).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Editar ordem' })).toHaveCount(0);
  await page.goto('/NovaOrdem');
  await expect(page.getByText('Meus veículos', { exact: true })).toBeVisible();
  await expect(page.getByText('Em manutenção', { exact: true }).first()).toBeVisible();
  await expect(page.getByText('Gol 2019', { exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Salvar ordem de serviço' })).toHaveCount(0);
  await page.screenshot({ path: 'docs/screenshots/cliente.png', fullPage: true });
  await page.setViewportSize({ width: 1280, height: 900 });
  await page.screenshot({ path: 'docs/screenshots/cliente-desktop.png', fullPage: true });
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth);
  expect(overflow).toBe(false);
  const publicDocs = await getFirestore(backend).collection('serviceOrders').get();
  expect(publicDocs.docs.every((d: any) => !('internalNotes' in d.data()) && !('laborCents' in d.data()) && !('cpf' in d.data()))).toBe(true);
  expect(errors).toEqual([]);
});

test('conta sem claim administrativa não abre painel mesmo com role admin no perfil', async ({ page }) => {
  const email = `impostor-${Date.now()}@sgo.test`, password = 'Teste123456!';
  const account = await getAuth(backend).createUser({ email, password });
  await getFirestore(backend).doc(`users/${account.uid}`).set({ role: 'admin' });
  await page.goto('/');
  await page.getByRole('button', { name: 'Login administrativo' }).click();
  await page.getByLabel('E-mail', { exact: true }).fill(email);
  await page.getByLabel('Senha', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await expect(page.getByText('Acesso não liberado', { exact: true })).toBeVisible();
  await page.goto('/NovaOrdem');
  await expect(page.getByText('Acesso não liberado', { exact: true })).toBeVisible();
  await expect(page.getByRole('tab')).toHaveCount(0);
});
