import { test, after } from 'node:test';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { initializeApp, deleteApp } from 'firebase/app';
import { getAuth, connectAuthEmulator, signInWithEmailAndPassword } from 'firebase/auth';
import { getFunctions, connectFunctionsEmulator, httpsCallable } from 'firebase/functions';
const require = createRequire(new URL('../functions/package.json', import.meta.url));
process.env.FIREBASE_AUTH_EMULATOR_HOST = '127.0.0.1:9099';
process.env.FIRESTORE_EMULATOR_HOST = '127.0.0.1:8080';
const { initializeApp: initAdmin, deleteApp: deleteAdmin } = require('firebase-admin/app');
const { getAuth: adminAuth } = require('firebase-admin/auth');
const { getFirestore } = require('firebase-admin/firestore');
const backend = initAdmin({ projectId: 'demo-sgo' }, 'backend-tests');
const app = initializeApp({ projectId: 'demo-sgo', apiKey: 'demo-key' }, 'backend-tests');
const auth = getAuth(app), functions = getFunctions(app, 'southamerica-east1');
connectAuthEmulator(auth, 'http://127.0.0.1:9099', { disableWarnings: true });
connectFunctionsEmulator(functions, '127.0.0.1', 5001);
after(async () => { await deleteApp(app); await deleteAdmin(backend); });
test('backend exige admin, provisiona duas placas sem senha no banco e força troca da senha', async () => {
  const suffix = Date.now(), email = `admin-${suffix}@sgo.test`, password = 'AdminTeste123!';
  await assert.rejects(httpsCallable(functions, 'saveCustomer')({ id: 'blocked', name: 'Intruso', phone: '51999999999' }), /conta|auth/i);
  const user = await adminAuth(backend).createUser({ email, password });
  await adminAuth(backend).setCustomUserClaims(user.uid, { admin: true });
  await signInWithEmailAndPassword(auth, email, password);
  const id = `c-${suffix}`;
  await httpsCallable(functions, 'saveCustomer')({ id, name: 'Ana Souza', phone: '(51) 99999-9999' });
  for (const plate of ['TST1A23', 'TST1234']) {
    await httpsCallable(functions, 'saveVehicle')({ customerId: id, plate, model: 'Onix 2020' });
    await assert.rejects(httpsCallable(functions, 'provisionClient')({ customerId: id, plate, password: '12345' }), /senha inicial/);
    await httpsCallable(functions, 'provisionClient')({ customerId: id, plate, password: 'SenhaInicial123' });
    await assert.rejects(httpsCallable(functions, 'provisionClient')({ customerId: id, plate, password: 'OutraSenha123' }), /já possui/);
    const vehicle = (await getFirestore(backend).doc(`vehicles/${plate}`).get()).data();
    const profile = (await getFirestore(backend).doc(`users/${vehicle.userId}`).get()).data();
    assert.equal(profile.customerId, id); assert.equal(profile.role, 'client'); assert.equal(profile.mustChangePassword, true);
    assert.equal(JSON.stringify({ vehicle, profile }).includes('SenhaInicial123'), false);
  }
  await httpsCallable(functions, 'saveVehicle')({ customerId: id, plate: 'RST1A23', model: 'Retomada' });
  const reserved = `reserved-${suffix}`;
  await getFirestore(backend).doc('vehicles/RST1A23').update({ provisioningUid: reserved });
  await adminAuth(backend).createUser({ uid: reserved, email: 'rst1a23@clientes.sgo.invalid', password: 'PrimeiraSenha123', disabled: true });
  const resumed = await httpsCallable(functions, 'provisionClient')({ customerId: id, plate: 'RST1A23', password: 'NovaTentativa123' });
  assert.equal((resumed.data as { resumed: boolean }).resumed, true);
  await assert.rejects(signInWithEmailAndPassword(auth, 'rst1a23@clientes.sgo.invalid', 'NovaTentativa123'));
  await signInWithEmailAndPassword(auth, 'rst1a23@clientes.sgo.invalid', 'PrimeiraSenha123');
  await signInWithEmailAndPassword(auth, 'tst1a23@clientes.sgo.invalid', 'SenhaInicial123');
  await assert.rejects(httpsCallable(functions, 'saveCustomer')({ id, name: 'Intruso', phone: '51999999999' }), /administradores/);
  await assert.rejects(httpsCallable(functions, 'changeInitialPassword')({ password: 'Nova123' }), /8 a 128/);
  await httpsCallable(functions, 'changeInitialPassword')({ password: 'Nova1234' });
  await assert.rejects(signInWithEmailAndPassword(auth, 'tst1a23@clientes.sgo.invalid', 'SenhaInicial123'));
  const login = await signInWithEmailAndPassword(auth, 'tst1a23@clientes.sgo.invalid', 'Nova1234');
  assert.equal((await getFirestore(backend).doc(`users/${login.user.uid}`).get()).data().mustChangePassword, false);
  await assert.rejects(httpsCallable(functions, 'changeInitialPassword')({ password: 'OutraSenha12345!' }), /já foi/);
});
